PDF_FILES := Adobe/pdf_reference_1-7.pdf
all: $(PDF_FILES)

# Taken from <http://www.adobe.com/devnet/pdf.html>
Adobe/pdf_reference_1-7.pdf:
	wget -cP Adobe http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf

