PNG_FILES := libpng/ccwn3p08.png
all: $(PNG_FILES)

# Taken from <http://www.libpng.org/pub/png/pngsuite.html>
libpng/ccwn3p08.png:
	wget -cP libpng http://www.libpng.org/pub/png/PngSuite/ccwn3p08.png
